### ISSUE TITLE
No script

### ISSUE THREAD

**Issue by Brutusn** [Brutusn/ScoutingVeghel#11]
Op een aantal vlakken "Geen javascript enabled" waarschuwing weergeven (plekken waar JS dus nodig is).

**Comment by Brutusn** [comment]
Won't fix.. todat iemand er last van heeft...

**Comment by Colin-TUE** [comment]
Goed artikel hierover: http://tobyho.com/2010/03/11/how-much-of-the-web-actually/

**Comment by Brutusn** [comment]
Artikel komt uit 2010 ;) is een eeuweigheid geleden :P

**Comment by Colin-TUE** [comment]
Zeker waar, maar nog steeds een mooi artikel. Niet alles hoef je meteen te volgen he :wink:
