### ISSUE TITLE
Messages and Text

### ISSUE THREAD

**Issue by Colin-TUE** [Brutusn/ScoutingVeghel#17]
We need to look at all messages and errors and make them more user-friendly and informative.

**Comment by Brutusn** [comment]
Don't forget the ajax status messeges for the contact form and for the verhuur.

**Comment by Colin-TUE** [comment]
Also do not forget the checking of colours (e.g. the location indicator next to contact)

**Comment by Colin-TUE** [comment]
Verder moeten we goed kijken naar consistent gebruik van hoofdletters

**Comment by Colin-TUE** [comment]
OP de confirm Pagina is de text shadow te veel (http://nieuw.scoutingveghel.nl/php/verhuur-confirm.php?key=9bfa03a316806ebc3864d9cc23acf1b0eb8db351bf5d0e6a297d1701). 

Dit komt omdat de class activiteiten is (voor de achtergrond). 

@Brutusn kun jij dit fixen?

**Comment by Brutusn** [comment]
Whoops :) Ja kan ik fixen
