### ISSUE TITLE
Indication if available

### ISSUE THREAD

**Issue by Colin-TUE** [Brutusn/ScoutingVeghel#22]
In the text we indicate that the user will get an indication if the blokhut is available. I do not see where this indication is. Maybe we can incorporate it with #20

**Comment by Brutusn** [comment]
Dit moet nog gemaakt worden. De indicatie zou verstuurd moeten worden zodra je van stap 1, naar stap 2 gaat.

Controleer huidige datum + 5 dagen.. als er iets is verhuurd geef dat terug.

**Comment by Colin-TUE** [comment]
Waarom van stap 1 naar stap 2. Ik zou verwachtend at als ik stap 2 ingevuld heb ik dan een indicatie krijg. Dit omdat dan beide gegevens bekend zijn. 

Verder denk ik dat van stap 1 naar stap 2 een gebruiksvriendelijke indicatie is die als extra toegevoegd kan worden maar zeker niet essentieel is, gezien de rede hierboven (en misschien zelfs als irritant ervaren kan worden).

**Comment by Colin-TUE** [comment]
Verder vind ik dat we of de indicatie of de kalender (#20) moeten implementeren voordat hij live gaat om een indicatie te hebben als je een optie wilt nemen.

**Comment by Colin-TUE** [comment]
Fixed by  39551e5
