### ISSUE TITLE
SSL certificates

### ISSUE THREAD

**Issue by eparon** [Brutusn/ScoutingVeghel#44]
Hello and congrats for your nice work on ScoutingVeghel!
I have one suggestion for you that can be considered as an improvement:
It would be nice if you served the website over https instead of http. That can be relatively easily achieved using an SSL certificate from an authority (for instance: letsencrypt) and by configuring your webserver accordingly.

**Comment by Brutusn** [comment]
https://blog.cpanel.com/announcing-cpanel-whms-official-lets-encrypt-with-autossl-plugin/

**Comment by Brutusn** [comment]
Our cpanel needs an update though

**Comment by Dutchsnof** [comment]
with our new hosting provider this works out of the box and has been implemented.
