### ISSUE TITLE
Menu scrolling inconsistent

### ISSUE THREAD

**Issue by Colin-TUE** [Brutusn/ScoutingVeghel#5]
Als je op een bepaalde "sub"-pagina zit (zoals bijvoorbeeld groepen) en je bent net niet uitgelijnd op het begin (hebt een klein omlaag beetje gescrold) en je klikt dan op de "sub"-pagina waar je op zit, dan vanaf dat moment update de menu balk niet meer als je naar een andere "sub"-pagina scrolt.

**Comment by Brutusn** [comment]
Nog steeds van toepassing?

**Comment by Colin-TUE** [comment]
I tried to reproduce this bug and It seems I am not able to. 

Maybe it is an idea to let SV test it and see if it pops up then.

**Comment by Brutusn** [comment]
I'll close it then, if the problem returns.. we open a new issue.
