### ISSUE TITLE
Praktijk begeleider toevoegen

### ISSUE THREAD

**Issue by Colin-TUE** [Brutusn/ScoutingVeghel#61]
aan de sectie waar ook de GeBe in zit

**Comment by Brutusn** [comment]
Is er een tekstje beschikbaar?

**Comment by Brutusn** [comment]
Ja is aanwezig in de mail van Benny!
[Info voor ouders.pdf](https://github.com/Brutusn/ScoutingVeghel/files/1228007/Info.voor.ouders.pdf)

**Comment by Colin-TUE** [comment]
Is dit al deployed op nieuw.scoutingveghel.nl?

**Comment by Brutusn** [comment]
Nee van de laatste 2 of 3 commits nog niet, vond de aanpassing te klein.
