### ISSUE TITLE
Verbeteren icoontjes speltakken

### ISSUE THREAD

**Issue by Colin-TUE** [Brutusn/ScoutingVeghel#62]

**Comment by Brutusn** [comment]
Voorstel:

[cake] 5 - 7 **jr.** - [calender] **zat.** 11:00 - 13:37.

**Comment by Colin-TUE** [comment]
Waarom zijn de lengtes van de dagen niet gelijk? Bijv. za versus woe

**Comment by Brutusn** [comment]
Geen idee, goede opmerking. Zal het morgen aanpassen.

Ik heb blijkbaar deze dingen door elkaar gehaald..

http://taaladvies.net/taal/advies/vraag/1728/afkortingen_van_de_dagen_van_de_week/
