### ISSUE TITLE
Mailen van Poetsrooster

### ISSUE THREAD

**Issue by Dutchsnof** [Brutusn/ScoutingVeghel#69]
Poetsrooster wordt niet meer elke maand gemailed. 

Ik heb even gezocht maar krijg niet gevonden waar deze afgevuurd worden. 
Cronjobs werken niet vanuit de omgeving van hostedby

**Comment by Colin-TUE** [comment]
Dat verklaart een boel aangezien de cron jobs te vinden zijn in de [cron folder](https://github.com/Brutusn/ScoutingVeghel/tree/main/cron) en als cronjob draaide op de vorige website.

**Comment by Dutchsnof** [comment]
Dit is inmiddels opgelost door powerautomate te gebruiken binnen office 365
